### ISSUE TITLE
Low Code Coverage

### ISSUE THREAD

**Issue by alexroan** [ChainAccelOrg/foundry-defi-stablecoin-f23#1]
Hey man, to ensure that every possible execution path executes as expected, 100% of code `Branches` should be covered by unit tests.

Printout of `forge coverage` (Note that this issue only really applies to the contracts within `src/`, so I've removed all other contracts from this printout):

```
| File                                                | % Lines         | % Statements     | % Branches     | % Funcs        |
|-----------------------------------------------------|-----------------|------------------|----------------|----------------|
| src/DSCEngine.sol                                   | 89.33% (67/75)  | 91.30% (84/92)   | 68.75% (11/16) | 89.66% (26/29) |
| src/DecentralizedStableCoin.sol                     | 66.67% (8/12)   | 69.23% (9/13)    | 50.00% (4/8)   | 100.00% (2/2)  |
| src/libraries/OracleLib.sol                         | 12.50% (1/8)    | 10.00% (1/10)    | 0.00% (0/4)    | 50.00% (1/2)   |
```

**Comment by PatrickAlphaC** [comment]
Fixed in 2649781 

It's at 97%... The last few % I don't think makes sense to cover for as they are essentially unreachable, but worse case conditionals. Let me know what you think.

You can make a coverage report with:
```
make coverage
```
