### ISSUE TITLE
Expensive collateral and price feed storage reads

### ISSUE THREAD

**Issue by alexroan** [ChainAccelOrg/foundry-defi-stablecoin-f23#4]
Hey dude, Not sure how deep you want to go into this one because I know it's meant for teaching purposes....

Both `s_collateralTokens` and `s_tokenAddressToPriceFeed` in DSCEngine.sol are in storage when they should really be immutable, like this:

```
address private immutable i_collateralToken0;
address private immutable i_collateralToken1;
address private immutable i_priceFeed0;
address private immutable i_priceFeed1;
```

Considering these already act as immutables, but are in storage, it stands to reason they should be moved. Also, judging by the number of reads from each of these on user hot paths, this change would save multiple thousands of gas.

However, this probably opens up a rabbit hole in learning material that you have to go down to explain why it's cheaper.. I've refrained from writing a PR in case you didn't want to open that can of worms for this one. LMK your thoughts.

**Comment by PatrickAlphaC** [comment]
At this point in the course, they will already know why that is cheaper! 

You're right, this would be better, but I'm going to close for now as I want to make it easily configurable for students to try their own combinations of collaterals. 

Yes, this level of attention to detail is good! I'll leave a note in the code about this.
